# Generated by Django 5.2.7 on 2025-10-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='driving_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
