# Generated by Django 5.2.7 on 2025-10-31 11:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('students', '0002_studentprofile_driving_time_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
