# Generated by Django 5.2.7 on 2025-11-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_notification_sent_at',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_boarding_today',
            field=models.BooleanField(default=True),
        ),
    ]
