# Generated by Django 5.2.7 on 2025-11-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_studentprofile_fcm_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='is_boarding_today',
            field=models.BooleanField(default=False),
        ),
    ]
