# Generated by Django 5.2.7 on 2025-11-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentprofile_is_boarding_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_notification_distance',
            field=models.IntegerField(blank=True, help_text='Last geofence threshold (in meters) for which a notification was sent', null=True),
        ),
    ]
