# Generated by Django 5.2.7 on 2025-11-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_alter_studentprofile_is_boarding_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnassignedStudent',
            fields=[
            ],
            options={
                'verbose_name': 'Unassigned Student',
                'verbose_name_plural': 'Unassigned Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.studentprofile',),
        ),
    ]
